{% set name = "polyline" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polyline-{{ version }}.tar.gz
  sha256: abc786b9332e84f27e6e59fd4fcbcb0c4b9af6a7f7b4175e2eb6c2786278deae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - polyline
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/polyline/
  summary: A Python implementation of Google's Encoded Polyline Algorithm Format.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
