{% set name = "polyline" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyline-{{ version }}.tar.gz
  sha256: 74cb5cea098dddf09d1a5a1f17af9184d371cbf3e9723de0194e530ec39ca1f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - polyline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/polyline/
  summary: A Python implementation of Google's Encoded Polyline Algorithm Format.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
